# Generated by Django 5.2.7 on 2025-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=15, null=True)),
                ('author', models.TextField(blank=True, max_length=15, null=True)),
                ('category', models.TextField(blank=True, max_length=15, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(blank=True, max_length=15, null=True)),
                ('Description', models.CharField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
